# Site settings
title: Data Science Africa
description: "Conference website."
banner: gazzelle.jpg
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.datascienceafrica.org" # the name of your domain
logo_url: img/logo.png
# logo_url: svg/min/logo.svg

email: info@datascienceafrica.org

notice:
  url: /dsa2017/
  text: | # From here to "school:"
    <div class="" style="
                        font-weight: bold; 
                        font-size: 18px;

                        ">Data Science Africa 2017</div>
    <div>June 17<sup>th</sup>  - July 21<sup>st</sup> 2017</div>
    <div>Arusha, Tanzania</div>

# Hero
hero:
    # hero_img: hero.jpg
    hero_img: gazzelle.jpg
    hero_img2: chimp.jpg
    hero_title: Data Science
    hero_description: Conference website.

# Contact form
api_token: # Enter API token here

# Testimonials
testimonials:
    testimonials_img: parallax.jpg


# Footer
copyright: © 2016 Data Science Africa Conference - All rights reserved
gem: 'kramdown'

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

analytics:
  google:
    tracking_id: UA-80484960-1

video:
  height: 315
  width: 560

# Theme Settings
google_verification:
